import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styled from "styled-components";
import Navbar2 from "@/components/Navbar2";
import Homepage from "@/components/Homepage";
import Features from "@/components/Features";



const ParentContainer = styled.main`
  width: 100vw;
  background-color: #12a9e0;
  padding: 0;
  height: 100vh;
`

const ParentContainer2 = styled.main`
  width: 100vw;
  padding: 0;
  background-color: #97f095;
  height: auto;
`

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <ParentContainer>
      <Navbar2/>
      <Homepage/>
      
      </ParentContainer>

      <ParentContainer2>

        <Features/>

      </ParentContainer2>

    </>
  )
}

const Container = styled.div`color: green;`


